<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Dal</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DalFacade\DalFacade.csproj" />
    <ProjectReference Include="..\tools\tools.csproj" />
	  <None Update="xml\*.xml">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
  </ItemGroup>

  <ItemGroup>
    <None Update="xml\customers.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\dal-config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\data-config.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\products.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="xml\sales.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
